In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3])

print(a)

element = a[1]
print(element)

[1 2 3]
2


In [3]:
# 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("matrix: ", matrix)

element = matrix[1, 2]
print(element)

matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [4]:
# Tao mang 0
a = np.zeros(5)
print(a)

# Tao mang so 1
a = np.ones(5)
print(a)

# Tao mang rong
a = np.empty(5)
print(a)

# tao mang tu 0 => 100
a = np.arange(100)
print(a)

# Tao mang voi khoang cach deu nhau
a = np.linspace(0, 10, num=5)
print(a)

a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1])

In [5]:
# Them xoa, sap xep mang

# Tao mang ban dau
arr = np.array([3, 1, 2, 4, 5])
print(arr)

# sap xep
arr = np.sort(arr)
print(arr)

# sap xep nguoc
arr = np.sort(arr)[::-1]
print(arr)

arr = np.append(arr, 100)
print(arr)

# Xoa di mot vi tri trong mang
arr = np.delete(arr, 3)
print(arr)

[3 1 2 4 5]
[1 2 3 4 5]
[5 4 3 2 1]
[  5   4   3   2   1 100]
[  5   4   3   1 100]


In [6]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [6, 6, 6]])

row = np.sort(arr, axis=1)
print(row)

column = np.sort(arr, axis=0)
print(column)


[[1 2 3]
 [4 6 8]
 [6 6 6]]
[[3 1 2]
 [4 6 6]
 [6 6 8]]


In [7]:
arr = np.array([[3, 1, 2],
                [4, 2, 8],
                [1, 7, 5]])

sap_xep_theo_hang = -np.sort(-arr, axis=1)
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0)
print(sap_xep_theo_cot)

[[3 2 1]
 [8 4 2]
 [7 5 1]]
[[4 7 8]
 [3 2 5]
 [1 1 2]]


In [8]:
# Tao mang 2D
arr = np.array([[1, 2, 3], [3, 4, 4]])

dimensions = arr.ndim
size = arr.size
shape = arr.shape

print(dimensions)
print(size)
print(shape)


2
6
(2, 3)


In [9]:
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
eshaped_arr = reshaped_arr.flatten()  # chuyen thanh mang 1 chieu
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
# Slices
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]
print(sub_arr)

sub_arr = arr[:-1]
print(sub_arr)

sub_arr = arr[-2:]
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [21]:
arr1 = np.array([0, 5, 2])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[0 5 2 4 5 6]


In [23]:
arr = np.array([1, 0, 1, 9, 5])
total = np.sum(arr)
print("Sum of arr:", total)

average = np.mean(arr)
print("Average of arr:", average)

max_value = np.max(arr)
min_value = np.min(arr)
print("Max value in arr:", max_value)
print("Min value in arr:", min_value)

std_deviation = np.std(arr)
print("Standard deviation:", std_deviation)

variance = np.var(arr)
print("Variance of array:", variance)

arr1 = np.array([6, 7, 8])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print(dot_product)



Sum of arr: 16
Average of arr: 3.2
Max value in arr: 9
Min value in arr: 0
Standard deviation: 3.3704599092705436
Variance of array: 11.360000000000001
107
